package Subviews;

import Controller.CtrlEditarTrabajador;
import Documents.GeneratorPDF_LBU;
import Model.LBU;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

public class MenuItem extends javax.swing.JPanel {

    public void setShowing(boolean showing) {
        this.showing = showing;
    }

    public ArrayList<SubMenuItem> getSubMenu() {
        return subMenu;
    }

    ImageIcon iconRigth = new ImageIcon(ClassLoader.getSystemResource("Images/IconArrowRight.png"));
    ImageIcon iconDown = new ImageIcon(ClassLoader.getSystemResource("Images/IconArrowUp.png"));

    private final ArrayList<SubMenuItem> subMenu = new ArrayList<>();
    private ActionListener act;

    public MenuItem(String menuName, int propuesto, int diferencia, int plantilla,
            int A, int B, int C, int D, int LV, ActionListener act, SubMenuItem... subMenu) {
        initComponents();
        lbName.setText(menuName);
        setLabel(lbPropuesto, String.valueOf(propuesto));
        setLabel(lbDiferencia, String.valueOf(diferencia));
        setDiferenciaColor(lbDiferencia, diferencia);
        setLabel(lbPlantilla, String.valueOf(plantilla));
        setNegrita(lbA, A);
        setNegrita(lbB, B);
        setNegrita(lbC, C);
        setNegrita(lbD, D);
        setNegrita(lbLV, LV);
        if (act != null) {
            this.act = act;
        }
        this.setSize(new Dimension(Integer.MAX_VALUE, 40));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 40));
        Icon.setIcon(iconRigth);

        for (int i = 0; i < subMenu.length; i++) {
            this.subMenu.add(subMenu[i]);
            subMenu[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPropuesto = new javax.swing.JLabel();
        lbDiferencia = new javax.swing.JLabel();
        lbPlantilla = new javax.swing.JLabel();
        lbA = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbB = new javax.swing.JLabel();
        lbC = new javax.swing.JLabel();
        lbD = new javax.swing.JLabel();
        lbLV = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Icon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(175, 196, 174));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lbPropuesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPropuesto.setText("Num...");

        lbDiferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDiferencia.setText("Num...");

        lbPlantilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlantilla.setText("Num..");

        lbA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbA.setText("Num..");

        lbName.setText("Supervisor...");

        lbB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbB.setText("Num...");

        lbC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbC.setText("Num...");

        lbD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbD.setText("Num...");

        lbLV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLV.setText("Num...");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconPrint.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPropuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbLV, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(lbPropuesto)
                            .addComponent(lbDiferencia)
                            .addComponent(lbPlantilla)
                            .addComponent(lbA)
                            .addComponent(lbB)
                            .addComponent(lbC)
                            .addComponent(lbD)
                            .addComponent(lbLV)
                            .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean showing = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (showing) {
            hideMenu();
        } else {
            showMenu();
        }
        if (act != null) {
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_formMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Supervisor = lbName.getText();
        LBU mod = new LBU();
        mod.setNombre_Supervisor(Supervisor);
        try {
            GeneratorPDF_LBU.LBUOperativoSupervisor(mod);
        } catch (Exception ex) {
            Logger.getLogger(CtrlEditarTrabajador.class.getName()).log(Level.SEVERE,
                    "Error para la funcion Generator_PDF: ", ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

//    Antiguo Metodo
    public void showMenu() {
        new Thread(() -> {
            for (int i = 0; i < subMenu.size(); i++) {
                sleep();
//                setBackground(new Color(113, 159, 113));
                subMenu.get(i).setVisible(true);
                Icon.setIcon(iconDown);
            }
            getParent().repaint();
            getParent().revalidate();
            showing = true;
        }).start();
    }

    public void hideMenu() {
        new Thread(() -> {
            for (int i = subMenu.size() - 1; i >= 0; i--) {
                sleep();
//                setBackground(new Color(242, 242, 242));
                subMenu.get(i).setVisible(false);
                subMenu.get(i).hideMenu();
                Icon.setIcon(iconRigth);
            }
            getParent().repaint();
            getParent().revalidate();
            showing = false;
        }).start();
    }

    private void sleep() {
        try {
            Thread.sleep(20);
        } catch (InterruptedException e) {
        }
    }

    private void setLabel(JLabel label, String text) {
        label.setText(text);
        label.setHorizontalAlignment(SwingConstants.CENTER);
    }

    private void setDiferenciaColor(JLabel label, int diferencia) {
        if (diferencia == 0) {
            label.setFont(label.getFont().deriveFont(Font.BOLD));
        } else if (diferencia < 0) {
            label.setFont(label.getFont().deriveFont(Font.BOLD));
            label.setForeground(Color.RED);
        } else {
            label.setFont(label.getFont().deriveFont(Font.BOLD));
            label.setForeground(new Color(0, 153, 0));
        }
    }

    private void setNegrita(JLabel label, int turno) {
        if (turno > 0) {
            label.setText(String.valueOf(turno));
            label.setFont(label.getFont().deriveFont(Font.BOLD));
            label.setHorizontalAlignment(SwingConstants.CENTER);
        } else {
            setLabel(label, String.valueOf(turno));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbA;
    public javax.swing.JLabel lbB;
    public javax.swing.JLabel lbC;
    public javax.swing.JLabel lbD;
    public javax.swing.JLabel lbDiferencia;
    public javax.swing.JLabel lbLV;
    public javax.swing.JLabel lbName;
    public javax.swing.JLabel lbPlantilla;
    public javax.swing.JLabel lbPropuesto;
    // End of variables declaration//GEN-END:variables
}
